name: Run Preprocessing on Push

on:
  push:
    branches:
      - master

jobs:
  preprocess:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run preprocessing script
        run: |
          python ./preprocessing/automate_Muhamad-Nizar-Dhiaudin.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          if git diff --quiet; then
            echo "No changes detected"
          else
            git add preprocessing/uci-retail_preprocessing.csv
            git commit -m "chore: auto-run preprocessing pipeline"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
